#!/usr/bin/env bash
#
# Install Pi Agent inside the OpenMinis Ubuntu sandbox.
# Pi is a terminal coding agent CLI (earendil-works/pi Agent Harness,
# license MIT) that we drive over stdin/stdout JSON-RPC from the
# Android host. This script is invoked once from the Android side
# (PiAgentService), after which `pi --mode rpc` is available as a
# normal command inside the sandbox.
#
# Strategy: install Node.js 22.x via apt / NodeSource, then
# `npm install -g --ignore-scripts @earendil-works/pi-coding-agent`.
# Ubuntu is glibc so the Bun binary might work, but we still prefer the
# Node.js path for reliability under PRoot.
#
# Layout after install:
#   /usr/local/bin/pi                       — POSIX shim → node + cli.js
#   /usr/local/lib/node_modules/...         — npm global install root
#   /var/minis/pi/.installed-<ver>          — sentinel (persistent bind)

set -euo pipefail

PI_VERSION="${PI_VERSION:-0.82.1}"
PI_PACKAGE="${PI_PACKAGE:-@earendil-works/pi-coding-agent@${PI_VERSION}}"
NODE_MIN_MAJOR="${NODE_MIN_MAJOR:-22}"
PI_HOME="${PI_HOME:-/var/minis/pi}"
PI_NPM_PREFIX="${PI_NPM_PREFIX:-/usr/local}"
SENTINEL="${PI_HOME}/.installed-${PI_VERSION}"
LOG_FILE="${PI_HOME}/install.log"

export DEBIAN_FRONTEND=noninteractive

log() {
    printf '[install_pi] %s\n' "$*" | tee -a "$LOG_FILE"
}

require_root() {
    if [ "$(id -u)" -ne 0 ]; then
        log "ERROR: install_pi.sh must run as root inside the sandbox"
        exit 1
    fi
}

ensure_pi_home() {
    mkdir -p "$PI_HOME"
    chmod 755 "$PI_HOME"
}

sentinel_present() {
    [ -f "$SENTINEL" ]
}

node_version_ok() {
    if ! command -v node >/dev/null 2>&1; then
        return 1
    fi
    local got
    got="$(node --version 2>/dev/null | sed -E 's/^v([0-9]+).*/\1/')"
    [ -n "$got" ] && [ "$got" -ge "$NODE_MIN_MAJOR" ]
}

apt_update_once() {
    if [ ! -f /var/minis/pi/.apt-updated ]; then
        log "Running apt-get update..."
        apt-get update -y >>"$LOG_FILE" 2>&1 || true
        touch /var/minis/pi/.apt-updated
    fi
}

install_node() {
    if node_version_ok; then
        log "Node already >= ${NODE_MIN_MAJOR}.x: $(node --version)"
        return 0
    fi

    apt_update_once
    log "Installing base deps + Node.js via apt..."
    apt-get install -y --no-install-recommends ca-certificates curl gnupg \
        >>"$LOG_FILE" 2>&1 || true

    apt-get install -y --no-install-recommends nodejs npm >>"$LOG_FILE" 2>&1 || true

    if ! node_version_ok; then
        log "Ubuntu nodejs too old or missing; installing NodeSource ${NODE_MIN_MAJOR}.x..."
        curl -fsSL "https://deb.nodesource.com/setup_${NODE_MIN_MAJOR}.x" \
            -o /tmp/nodesource_setup.sh >>"$LOG_FILE" 2>&1 || {
            log "ERROR: failed to fetch NodeSource setup script"
            return 1
        }
        bash /tmp/nodesource_setup.sh >>"$LOG_FILE" 2>&1 || true
        apt-get install -y --no-install-recommends nodejs >>"$LOG_FILE" 2>&1 || {
            log "ERROR: failed to install Node.js; aborting"
            return 1
        }
    fi

    if ! node_version_ok; then
        log "ERROR: Node.js still not detected after install (got: $(node --version 2>/dev/null || echo none))"
        return 1
    fi
    log "Node ready: $(node --version) (npm $(npm --version 2>/dev/null || echo n/a))"
}

install_pi() {
    log "Installing ${PI_PACKAGE} via npm (prefix=${PI_NPM_PREFIX})..."
    npm install -g --ignore-scripts "$PI_PACKAGE" --prefix "$PI_NPM_PREFIX" 2>>"$LOG_FILE" || {
        log "ERROR: npm install of pi failed; see $LOG_FILE"
        return 1
    }

    local pi_cli
    pi_cli="${PI_NPM_PREFIX}/lib/node_modules/@earendil-works/pi-coding-agent/dist/cli.js"
    if [ ! -f "$pi_cli" ]; then
        pi_cli="$(find "${PI_NPM_PREFIX}/lib/node_modules" -path '*/pi-coding-agent/dist/cli.js' 2>/dev/null | head -1 || true)"
    fi
    if [ -z "${pi_cli:-}" ] || [ ! -f "$pi_cli" ]; then
        log "ERROR: pi cli.js not found after install"
        return 1
    fi
    log "Pi installed at ${pi_cli}"
    printf '%s\n' "$pi_cli" > "${PI_HOME}/cli.path"
}

write_shim() {
    local shim_path="/usr/local/bin/pi"
    local pi_cli
    if [ -f "${PI_HOME}/cli.path" ]; then
        pi_cli="$(cat "${PI_HOME}/cli.path")"
    else
        pi_cli="${PI_NPM_PREFIX}/lib/node_modules/@earendil-works/pi-coding-agent/dist/cli.js"
    fi
    if [ -L "$shim_path" ] || [ -e "$shim_path" ]; then
        rm -f "$shim_path" 2>/dev/null || true
    fi
    cat >"$shim_path" <<SHIM
#!/bin/sh
# Generated by install_pi.sh — Node.js entry for pi-coding-agent on Ubuntu.
exec /usr/bin/env node \\
    "${pi_cli}" \\
    "\$@"
SHIM
    chmod 0755 "$shim_path"
    log "Wrote pi shim to $shim_path -> $pi_cli"
}

write_profile_d() {
    cat >/etc/profile.d/pi.sh <<'PROFILE'
# pi-coding-agent: wired in by OpenMinis Ubuntu Agent. See install_pi.sh / pi-install.
export PI_HOME="${PI_HOME:-/var/minis/pi}"
export PATH="${PATH:-/usr/local/bin:/usr/bin:/bin}"
type pi >/dev/null 2>&1 || true
PROFILE
    chmod 0644 /etc/profile.d/pi.sh
}

write_sentinel() {
    {
        echo "version=${PI_VERSION}"
        echo "node=$(node --version)"
        echo "npm=$(npm --version 2>/dev/null || echo n/a)"
        echo "distro=ubuntu"
        echo "installed_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "install_log=${LOG_FILE}"
    } >"$SENTINEL"
    log "Wrote sentinel: $SENTINEL"
}

verify_pi() {
    log "Verifying pi --version..."
    if ! pi --version >>"$LOG_FILE" 2>&1; then
        log "ERROR: pi --version failed"
        return 1
    fi
    log "pi OK: $(pi --version 2>&1 | head -n1)"
}

main() {
    require_root
    ensure_pi_home

    if sentinel_present; then
        log "Sentinel already present at $SENTINEL; skipping install"
        write_shim
        write_profile_d
        exit 0
    fi

    install_node
    install_pi
    write_shim
    write_profile_d
    write_sentinel
    verify_pi

    log "Done. Pi Agent ${PI_VERSION} ready on Ubuntu (RPC mode: pi --mode rpc)"
}

main "$@"
